branches:
  refactor/oauth-event-handlers:
    purpose: Refactor OAuth event handler implementations
    status: Active development
    last_sync: $(date +"%Y-%m-%d")
    sync_target: origin/main
    description: >
      Branch dedicated to refactoring OAuth event handlers to improve code organization
      and maintainability. Focuses on restructuring the event handling logic for OAuth
      authentication flows.
