name: Update Branches with Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Update branches with main
        run: |
          # Get all branches except main
          for branch in $(git branch -r | grep -v 'origin/main' | grep -v 'HEAD' | sed 's/origin\///'); do
            echo "Processing branch: $branch"
            git checkout $branch
            git merge origin/main --no-edit || {
              echo "Merge conflict in $branch, skipping..."
              git merge --abort
              continue
            }
            git push origin $branch
          done
